### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by intgr** [MTG/acousticbrainz-gui#16]
When I run acousticbrainz-gui on my collection, it runs for a while and then stops with the following messages in console:
````
QProcessPrivate::createPipe: Cannot create pipe 0x1530af8: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1534318: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1534310: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1534310: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x15342e8: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1037ed8: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x153a5b0: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1038a20: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0xfe73e8: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0xfe7858: Too many open files
Couldn't open cache file "/home/XXXXX/.cache/AcousticBrainz/Submitter/submitted.log" for writing
QProcessPrivate::createPipe: Cannot create pipe 0x1425c68: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1425c20: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1425c20: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x10389d8: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x152fb18: Too many open files
Couldn't open cache file "/home/XXXXX/.cache/AcousticBrainz/Submitter/submitted.log" for writing
QProcessPrivate::createPipe: Cannot create pipe 0xfd4408: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0xfd43c0: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0xfe76a0: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x1038878: Too many open files
QProcessPrivate::createPipe: Cannot create pipe 0x10386c8: Too many open files
Couldn't open cache file "/home/XXXXX/.cache/AcousticBrainz/Submitter/submitted.log" for writing
```

````
# ls -lav /proc/920/fd
[...]
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1017 -> /tmp/Submitter.LLy920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1018 -> /tmp/Submitter.ZXN920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1019 -> /tmp/Submitter.sJy920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1020 -> /tmp/Submitter.rqq920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1021 -> /tmp/Submitter.YcG920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1022 -> /tmp/Submitter.mAB920
lrwx------ 1 XXXXX XXXXX 64 May 19 16:48 1023 -> /tmp/Submitter.FSg920
```

**Comment by intgr** [comment]
When I click "Stop" after it freezes, it crashes for good. I get the following traceback:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6593160 in QProcess::terminate() () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff6593160 in QProcess::terminate() () from /usr/lib/libQt5Core.so.5
#1  0x0000000000410bf9 in Extractor::cancel() ()
#2  0x000000000040f859 in ProgressDialog::stop() ()
#3  0x00007ffff6698ff9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff7a412b2 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff77943f5 in ?? () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff7795019 in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff77951d4 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff76dc708 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff76993dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff769f0e3 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff66689eb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff769dbfa in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff76f4dd0 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff76f6f43 in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff76993dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff769e820 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff66689eb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff6b92ec2 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#19 0x00007ffff6b94a75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#20 0x00007ffff6b7995f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#21 0x00007fffec7f7430 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#22 0x00007ffff53e19fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff53e1ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff53e1d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff66c0de7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff6666482 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff666de5c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#28 0x000000000040c613 in main ()
```
